### ISSUE TITLE
Error when .DS_Store is present in themes dir.

### ISSUE THREAD

**Issue by kalfheim** [gergo85/oc-quick-edit#1]
Got this error when adding widget:
"opendir(themes/.DS_Store/pages): failed to open dir: Not a directory" on line 6 of /home/vagrant/Code/october/plugins/indikator/qedit/reportwidgets/qedit/partials/_widget.htm"

Basically you have to ignore files/directories beginning with a dot. Also, you should be using the Laravel API to do this - with something like `File::files()` or `File::directories()`.

**Comment by gergo85** [comment]
Thank you for reporting this issue. I fixed it and I updated the plugin.
